### ISSUE TITLE
Move badge URL regexps to a separate module

### ISSUE THREAD

**Issue by eush77** [wooorm/remark-strip-badges#2]
I can easily imagine other use cases where I would need to detect whether image URL points to a badge. [The list of badge regexps](https://github.com/wooorm/mdast-strip-badges/blob/c04345e1229fdfc4ed7ec420364f94c9db598bb2/index.js#L16-19) in this module is useful on its own for that purpose and is self contained.

Growing it here means that everyone else who needs the same functionality would need to do the same. Thought on separating this list (or perhaps `isBadge` function as a whole) into a different module?

**Comment by wooorm** [comment]
Yeah, completely for this! I find that when writing modules I find so many more submodules I could write, that when diverging into that immediately takes up too much time, that I’d rather do that later.

Hopefully somewhere today!
